import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { getMenu } from './api/hello'

const Home = () => {
  const data = getMenu()
  
  return (
    <>
      <Head>
        <title>Jabee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <h1>{data}</h1>
    </div>
    </>
  )
}

export default Home
